repos:
-  repo: local
   hooks:

   -  id: fprettify
      name: fprettify
      entry: bash -c 'fprettify -r ./source/'
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
      verbose: true

   -  id: funit
      name: funit
      entry: run_funit.sh
      language: script
      types: [python]
      always_run: true
      verbose: true
